version: '3.8'

services:
  app:
    image: ghcr.io/gigachad-dev/telegram-twitch-notifications:latest
    ports:
      - 5005:3003
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg-data:
