version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tg
      POSTGRES_PASSWORD: tg
      POSTGRES_DB: tg
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: telegram_twitch_notifications
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tg@example.com
      PGADMIN_DEFAULT_PASSWORD: tg
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
